### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by TzviPM** [marcj/TypeRunner#11]
This seems like an interesting project, and I'd love to use some of the concepts here for my own toy compiler. Can you please clarify what license this code is released under?

Unless you have reason not to, please consider choosing an OSI Approved license from https://spdx.org/licenses/. Examples include:

*   [Zero-Clause BSD (0BSD)](http://spdx.org/licenses/0BSD.html)
*   [MIT No Attribution License (MIT-0)](http://opensource.org/licenses/MIT-0)

**Comment by TzviPM** [comment]
Note: it seems much of the logic here is also easy under Apache 2.0 based on Github's ToS and your issue https://github.com/microsoft/TypeScript/issues/47658

**Comment by marcj** [comment]
Fixed

**Comment by TzviPM** [comment]
Thanks @marcj is your work based on this paper at all? I'm curious as to how you came up with the byte code approach. I love the work you're doing here :)


Sergey, I., & Clarke, D. (2011). From type checking by recursive descent to type checking with an abstract machine. Proceedings of the Eleventh Workshop on Language Descriptions, Tools and Applications, 1–7. https://doi.org/10.1145/1988783.1988785

**Comment by marcj** [comment]
@TzviPM thanks. It's not based on a paper, I didn't know there is literature about it (I also didn't look for any), so it's more intuitive off the top of my head from my experience. felt only natural to me to "serialise" as much expensive-to-get knowledge as possible to some format (in this case bytecode) and then execute the program on another abstraction (type level)

**Comment by marcj** [comment]
@TzviPM do you need help implementing this approach in Flutter?

**Comment by TzviPM** [comment]
> @TzviPM do you need help implementing this approach in Flutter?

Thanks for the offer @marcj. I'm not currently working on Flutter, but perhaps someone on the core dart team would be interested.

**Comment by marcj** [comment]
@TzviPM thanks! I thought you were since you have it in your bio. Could you please refer/intro me to some core member that might be interested?

**Comment by TzviPM** [comment]
I'm wondering if @munificent would be a good contact. Last we spoke, he was working on the formal dart specification. Perhaps this could lend itself to part of a formal type semantics. I also wonder if this could be impactful for the dart VM for smaller byte-size representation of runtime types.
