### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by justExploringTheWorld** [marcj/TypeRunner#13]
Hello, it was nice to read your approach to the solution. I have a question, and I will be glad if you answer on it, because I some kind of newbie in compilers:

I read somewhere that TS language service use AST caching mechanism in order to improve type-checking performance. But the main issue (in my opinion) that it needs to rebuild AST for file when the file from import segment has changed, even if source file didn't changed. The reason why - because it may affect other files type correctness. I don't know which approach they use, but can it possible to use yours to implement faster type checking for files, without rebuilding ASTs even if file from import segment has changed? We can use some kind of dependencies graph, so, when file changed, we of course will need to rebuild and cache AST for it, but we can also know which files uses types from them (dependencies graph) and re-check their cached AST with fast virtual machine.

What you think? Is it possible? Or we always need to rebuild AST for file when file from import segment has changed (even if file data didn't changed at all)?

P.S. Sorry for my bad English 🙂

**Comment by marcj** [comment]
TSC uses AST caching + type caching (types/symbols are cached at AST nodes), that's very different to our approach of caching the bytecode.

> but can it possible to use yours to implement faster type checking for files, without rebuilding ASTs even if file from import segment has changed

This is already implemented. The AST is only created once for every file, completely unrelated to other files.
