### ISSUE TITLE
Incremental checking

### ISSUE THREAD

**Issue by goloveychuk** [marcj/TypeRunner#8]
Very interesting idea.
So, when one file is changed, you still need to execute all bytecodes for all files, because one file could affect any other. 
For a big codebase (which usually it is, cause you're targeting enterprise) do you think executing all bytecodes will be fast?

If not, mb the solution could be to store a relation map between types/nodes and exec only affected bytecode.

**Comment by marcj** [comment]
> do you think executing all bytecodes will be fast?

Yes. Also, unchanged bytecode modules have a cache implemented for all sorts of types, so it's not going to reinterpret all of it just because one file changed at least for the language server. For the CLI it will be fast enough since it's roughly 500-1000x faster compared to tsc.
